# Site settings
title: Samuel Delamarter
email:
description: > # this means to ignore newlines until "baseurl:"
  Awesome description of site here. Edit this
  line in _config.yml. Appears: document head meta (for
  Google search results), feed.xml site description, footer.
baseurl: "" # the subpath of your site, e.g. /blog/
#CURRENTLY DO NOT HAVE ANYTHING OTHER THAN sam99676.gethub.io
url: "" # the base hostname & protocol for your site

twitter_username: SDelamarter44
github_username:  sam99676

# Build settings
markdown: kramdown
